dist: focal
language: node_js
node_js:
  - v22.16.0
cache:
  directories:
    - node_modules
before_install:
  - cd service
  - npm i -g pnpm@9.14.2
install:
  - pnpm install
services:
  - mysql
script:
  - pnpm run test:ci:coverage

