version: '3.8'

services:
  matrix-adapter:
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    container_name: alkemio_dev_matrix_adapter
    hostname: matrix-adapter
    image: alkemio/matrix-adapter:v0.8.0
    platform: linux/amd64
    environment:
      - RABBITMQ_HOST
      - RABBITMQ_USER
      - RABBITMQ_PASSWORD
      - SYNAPSE_HOMESERVER_NAME
      - SYNAPSE_SERVER_URL
      - SYNAPSE_SERVER_NAME
      - MATRIX_AS_TOKEN
      - MATRIX_HS_TOKEN
#      - MATRIX_BOT_ACTOR_ID
      - LOGGING_CONSOLE_ENABLED
      - LOGGING_LEVEL_CONSOLE=debug
      - ENVIRONMENT=dev
    restart: always
    networks:
      - alkemio_dev_net
    ports:
      - 8280
    command: sh -c "/app/matrix-adapter"
