// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	// Reverse Mapping: Entity ID → Actor ID (agent.id)
	// These queries support the Matrix → Alkemio direction
	// Lookup agent ID from user.id (entity ID)
	GetAgentIDByUserID(ctx context.Context, id pgtype.UUID) (pgtype.UUID, error)
	// Lookup agent ID from virtual_contributor.id (entity ID)
	GetAgentIDByVCID(ctx context.Context, id pgtype.UUID) (pgtype.UUID, error)
	// Forward Mapping: Actor ID (agent.id) → Entity ID (user.id or virtual_contributor.id)
	// These queries support the Alkemio → Matrix direction
	// Lookup user.id by the agent ID (actor ID)
	GetUserIDByAgentID(ctx context.Context, agentid pgtype.UUID) (pgtype.UUID, error)
	// Lookup virtual_contributor.id by the agent ID (actor ID)
	GetVCIDByAgentID(ctx context.Context, agentid pgtype.UUID) (pgtype.UUID, error)
}

var _ Querier = (*Queries)(nil)
