// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getAgentIDByUserID = `-- name: GetAgentIDByUserID :one

SELECT "agentId" FROM "user" WHERE id = $1
`

// Reverse Mapping: Entity ID → Actor ID (agent.id)
// These queries support the Matrix → Alkemio direction
// Lookup agent ID from user.id (entity ID)
func (q *Queries) GetAgentIDByUserID(ctx context.Context, id pgtype.UUID) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, getAgentIDByUserID, id)
	var agentId pgtype.UUID
	err := row.Scan(&agentId)
	return agentId, err
}

const getAgentIDByVCID = `-- name: GetAgentIDByVCID :one
SELECT "agentId" FROM virtual_contributor WHERE id = $1
`

// Lookup agent ID from virtual_contributor.id (entity ID)
func (q *Queries) GetAgentIDByVCID(ctx context.Context, id pgtype.UUID) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, getAgentIDByVCID, id)
	var agentId pgtype.UUID
	err := row.Scan(&agentId)
	return agentId, err
}

const getUserIDByAgentID = `-- name: GetUserIDByAgentID :one

SELECT id FROM "user" WHERE "agentId" = $1
`

// Forward Mapping: Actor ID (agent.id) → Entity ID (user.id or virtual_contributor.id)
// These queries support the Alkemio → Matrix direction
// Lookup user.id by the agent ID (actor ID)
func (q *Queries) GetUserIDByAgentID(ctx context.Context, agentid pgtype.UUID) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, getUserIDByAgentID, agentid)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const getVCIDByAgentID = `-- name: GetVCIDByAgentID :one
SELECT id FROM virtual_contributor WHERE "agentId" = $1
`

// Lookup virtual_contributor.id by the agent ID (actor ID)
func (q *Queries) GetVCIDByAgentID(ctx context.Context, agentid pgtype.UUID) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, getVCIDByAgentID, agentid)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}
