// Code generated by gen-events. DO NOT EDIT.

import type {
  AddReactionRequest,
  AddReactionResponse,
  BaseResponse,
  BatchAddMemberRequest,
  BatchAddMemberResponse,
  BatchAddSpaceMemberRequest,
  BatchAddSpaceMemberResponse,
  BatchRemoveMemberRequest,
  BatchRemoveMemberResponse,
  BatchRemoveSpaceMemberRequest,
  BatchRemoveSpaceMemberResponse,
  CreateRoomRequest,
  CreateSpaceRequest,
  DeleteMessageRequest,
  DeleteRoomRequest,
  DeleteSpaceRequest,
  GetMessageRequest,
  GetMessageResponse,
  GetReactionRequest,
  GetReactionResponse,
  GetRoomRequest,
  GetRoomResponse,
  GetSpaceRequest,
  GetSpaceResponse,
  ListRoomsRequest,
  ListRoomsResponse,
  ListSpacesRequest,
  ListSpacesResponse,
  MessageReceivedPayload,
  RemoveReactionRequest,
  SendMessageRequest,
  SendMessageResponse,
  SetParentRequest,
  SyncActorRequest,
  UpdateRoomRequest,
  UpdateSpaceRequest,
} from './dto';

/**
 * Command registry mapping topics to their request/response types.
 * Use RequestFor<T> and ResponseFor<T> type helpers for type-safe access.
 */
export const Commands = {
  'communication.actor.sync': {
    request: {} as SyncActorRequest,
    response: {} as BaseResponse,
  },
  'communication.hierarchy.set_parent': {
    request: {} as SetParentRequest,
    response: {} as BaseResponse,
  },
  'communication.message.delete': {
    request: {} as DeleteMessageRequest,
    response: {} as BaseResponse,
  },
  'communication.message.get': {
    request: {} as GetMessageRequest,
    response: {} as GetMessageResponse,
  },
  'communication.message.send': {
    request: {} as SendMessageRequest,
    response: {} as SendMessageResponse,
  },
  'communication.reaction.add': {
    request: {} as AddReactionRequest,
    response: {} as AddReactionResponse,
  },
  'communication.reaction.get': {
    request: {} as GetReactionRequest,
    response: {} as GetReactionResponse,
  },
  'communication.reaction.remove': {
    request: {} as RemoveReactionRequest,
    response: {} as BaseResponse,
  },
  'communication.room.create': {
    request: {} as CreateRoomRequest,
    response: {} as BaseResponse,
  },
  'communication.room.delete': {
    request: {} as DeleteRoomRequest,
    response: {} as BaseResponse,
  },
  'communication.room.get': {
    request: {} as GetRoomRequest,
    response: {} as GetRoomResponse,
  },
  'communication.room.list': {
    request: {} as ListRoomsRequest,
    response: {} as ListRoomsResponse,
  },
  'communication.room.member.batch.add': {
    request: {} as BatchAddMemberRequest,
    response: {} as BatchAddMemberResponse,
  },
  'communication.room.member.batch.remove': {
    request: {} as BatchRemoveMemberRequest,
    response: {} as BatchRemoveMemberResponse,
  },
  'communication.room.update': {
    request: {} as UpdateRoomRequest,
    response: {} as BaseResponse,
  },
  'communication.space.create': {
    request: {} as CreateSpaceRequest,
    response: {} as BaseResponse,
  },
  'communication.space.delete': {
    request: {} as DeleteSpaceRequest,
    response: {} as BaseResponse,
  },
  'communication.space.get': {
    request: {} as GetSpaceRequest,
    response: {} as GetSpaceResponse,
  },
  'communication.space.list': {
    request: {} as ListSpacesRequest,
    response: {} as ListSpacesResponse,
  },
  'communication.space.member.batch.add': {
    request: {} as BatchAddSpaceMemberRequest,
    response: {} as BatchAddSpaceMemberResponse,
  },
  'communication.space.member.batch.remove': {
    request: {} as BatchRemoveSpaceMemberRequest,
    response: {} as BatchRemoveSpaceMemberResponse,
  },
  'communication.space.update': {
    request: {} as UpdateSpaceRequest,
    response: {} as BaseResponse,
  },
} as const;

/**
 * Outgoing events emitted by the adapter (no request, only payload).
 */
export const OutgoingEvents = {
  'communication.message.received': {
    payload: {} as MessageReceivedPayload,
  },
} as const;

// ============================================================================
// Type Helpers
// ============================================================================

/** All command topics */
export type CommandTopic = keyof typeof Commands;

/** Get the request type for a given command topic */
export type RequestFor<T extends CommandTopic> = (typeof Commands)[T]['request'];

/** Get the response type for a given command topic */
export type ResponseFor<T extends CommandTopic> = (typeof Commands)[T]['response'];

/** All outgoing event topics */
export type OutgoingEventTopic = keyof typeof OutgoingEvents;

/** Get the payload type for a given outgoing event topic */
export type PayloadFor<T extends OutgoingEventTopic> = (typeof OutgoingEvents)[T]['payload'];
