// Code generated by tygo. DO NOT EDIT.

//////////
// source: actor.go

/**
 * SyncActorRequest ensures an actor exists in Matrix and updates their profile.
 * This is an idempotent operation - calling with the same data has no effect.
 * Topic: communication.actor.sync
 */
export interface SyncActorRequest {
  actor_id: AlkemioActorID;
  display_name: string;
  avatar_url?: string;
}
/**
 * SyncActorResponse confirms the actor sync operation.
 */
export interface SyncActorResponse {
  BaseResponse: BaseResponse;
}

//////////
// source: batch.go

/**
 * BatchAddMemberRequest adds a single actor to multiple rooms.
 * Topic: communication.room.member.batch.add
 */
export interface BatchAddMemberRequest {
  actor_id: AlkemioActorID;
  alkemio_room_ids: AlkemioRoomID[];
}
/**
 * BatchAddMemberResponse returns per-room results.
 */
export interface BatchAddMemberResponse {
  BaseResponse: BaseResponse;
  /**
   * Results maps AlkemioRoomID (string) to operation result.
   * Only populated if BaseResponse.Success is true (batch was processed).
   */
  results?: { [key: string]: BaseResponse};
}
/**
 * BatchRemoveMemberRequest removes a single actor from multiple rooms.
 * Topic: communication.room.member.batch.remove
 */
export interface BatchRemoveMemberRequest {
  actor_id: AlkemioActorID;
  alkemio_room_ids: AlkemioRoomID[];
  reason?: string;
}
/**
 * BatchRemoveMemberResponse returns per-room results.
 */
export interface BatchRemoveMemberResponse {
  BaseResponse: BaseResponse;
  results?: { [key: string]: BaseResponse};
}

//////////
// source: error.go

/**
 * ErrorCode represents categorized error types for programmatic handling.
 */
export type ErrorCode = string;
/**
 * ErrCodeInvalidParam indicates request validation failed (invalid payload or parameters).
 */
export const ErrCodeInvalidParam: ErrorCode = "INVALID_PARAM";
/**
 * ErrCodeRoomNotFound indicates the referenced room does not exist.
 */
export const ErrCodeRoomNotFound: ErrorCode = "ROOM_NOT_FOUND";
/**
 * ErrCodeSpaceNotFound indicates the referenced space does not exist.
 */
export const ErrCodeSpaceNotFound: ErrorCode = "SPACE_NOT_FOUND";
/**
 * ErrCodeActorNotFound indicates the referenced actor does not exist.
 */
export const ErrCodeActorNotFound: ErrorCode = "ACTOR_NOT_FOUND";
/**
 * ErrCodeMatrixError indicates a Matrix SDK/homeserver error.
 */
export const ErrCodeMatrixError: ErrorCode = "MATRIX_ERROR";
/**
 * ErrCodeInternalError indicates an unexpected system error.
 */
export const ErrCodeInternalError: ErrorCode = "INTERNAL_ERROR";
/**
 * ErrCodeNotAllowed indicates the operation is not permitted.
 */
export const ErrCodeNotAllowed: ErrorCode = "NOT_ALLOWED";
/**
 * ErrorResponse contains structured error information.
 */
export interface ErrorResponse {
  code: ErrorCode;
  message: string;
  details?: string; // Optional technical details
}
/**
 * BaseResponse is the standard response structure for all command responses.
 * Operations that return only status use this directly.
 * Operations with additional data embed this struct.
 */
export interface BaseResponse {
  success: boolean;
  error?: ErrorResponse;
}

//////////
// source: event.go

/**
 * MessageReceivedPayload represents the event when a message is received.
 */
export interface MessageReceivedPayload {
  roomId: string;
  roomName: string;
  message: Message;
  actorID: string; // The actor who received the message (the bot)
  communityId?: string;
}
/**
 * Message represents a Matrix message event.
 */
export interface Message {
  id: string;
  message: string;
  threadID?: string;
  sender: string;
  timestamp: number /* int64 */;
  reactions: Reaction[];
}
/**
 * Reaction represents a reaction to a message.
 */
export interface Reaction {
  id: string;
  emoji: string;
  sender: string;
  timestamp: number /* int64 */;
  messageId: string;
}

//////////
// source: hierarchy.go

/**
 * SetParentRequest establishes parent-child relationship for a room or subspace.
 * Topic: communication.hierarchy.set_parent
 */
export interface SetParentRequest {
  /**
   * ChildID is the AlkemioRoomID (for rooms) or AlkemioContextID (for subspaces) to add as child.
   */
  child_id: string;
  is_space: boolean;
  parent_context_id: AlkemioContextID;
  order?: string;
  suggested?: boolean;
}
/**
 * SetParentResponse confirms the hierarchy update.
 */
export interface SetParentResponse {
  BaseResponse: BaseResponse;
}

//////////
// source: message.go

/**
 * MessageDto represents a message in a room.
 */
export interface MessageDto {
  id: MessageID;
  content: string;
  sender_actor_id: AlkemioActorID;
  timestamp: string;
  reactions: ReactionDto[];
  thread_id?: MessageID;
}
/**
 * SendMessageRequest sends a text message to a room.
 * Topic: communication.message.send
 */
export interface SendMessageRequest {
  alkemio_room_id: AlkemioRoomID;
  sender_actor_id: AlkemioActorID;
  content: string; // Markdown supported
  parent_message_id?: MessageID; // For threads
}
/**
 * SendMessageResponse returns the message ID and timestamp.
 */
export interface SendMessageResponse {
  BaseResponse: BaseResponse;
  message_id: MessageID;
  timestamp: string; // UTC time from Matrix
}
/**
 * GetMessageRequest retrieves details of a specific message.
 * Topic: communication.message.get
 */
export interface GetMessageRequest {
  alkemio_room_id: AlkemioRoomID;
  message_id: MessageID;
}
/**
 * GetMessageResponse returns message details.
 */
export interface GetMessageResponse {
  BaseResponse: BaseResponse;
  message: MessageDto;
}
/**
 * DeleteMessageRequest redacts/deletes a message.
 * Topic: communication.message.delete
 */
export interface DeleteMessageRequest {
  alkemio_room_id: AlkemioRoomID;
  message_id: MessageID;
  sender_actor_id: AlkemioActorID;
  reason?: string;
}
/**
 * DeleteMessageResponse confirms deletion.
 */
export interface DeleteMessageResponse {
  BaseResponse: BaseResponse;
}

//////////
// source: reaction.go

/**
 * ReactionDto represents a reaction to a message.
 */
export interface ReactionDto {
  id: ReactionID;
  emoji: string;
  sender_actor_id: AlkemioActorID;
  timestamp: string;
}
/**
 * AddReactionRequest adds an emoji reaction to a message.
 * Topic: communication.reaction.add
 */
export interface AddReactionRequest {
  alkemio_room_id: AlkemioRoomID;
  message_id: MessageID;
  sender_actor_id: AlkemioActorID;
  emoji: string;
}
/**
 * AddReactionResponse returns the reaction ID.
 */
export interface AddReactionResponse {
  BaseResponse: BaseResponse;
  reaction_id: ReactionID;
}
/**
 * RemoveReactionRequest removes a previously added reaction.
 * Topic: communication.reaction.remove
 */
export interface RemoveReactionRequest {
  alkemio_room_id: AlkemioRoomID;
  reaction_id: ReactionID;
  sender_actor_id: AlkemioActorID;
}
/**
 * RemoveReactionResponse confirms removal.
 */
export interface RemoveReactionResponse {
  BaseResponse: BaseResponse;
}
/**
 * GetReactionRequest retrieves details of a specific reaction.
 * Topic: communication.reaction.get
 */
export interface GetReactionRequest {
  alkemio_room_id: AlkemioRoomID;
  reaction_id: ReactionID;
}
/**
 * GetReactionResponse returns reaction details.
 */
export interface GetReactionResponse {
  BaseResponse: BaseResponse;
  reaction: ReactionDto;
}

//////////
// source: room.go

/**
 * CreateRoomRequest creates a new communication channel.
 * Topic: communication.room.create
 */
export interface CreateRoomRequest {
  alkemio_room_id: AlkemioRoomID;
  type: RoomType;
  name?: string; // Ignored for 'direct'
  initial_members?: AlkemioActorID[];
  topic?: string;
  avatar_url?: string;
  parent_context_id?: AlkemioContextID;
  join_rule?: JoinRule;
}
/**
 * CreateRoomResponse confirms room creation.
 */
export interface CreateRoomResponse {
  BaseResponse: BaseResponse;
}
/**
 * GetRoomRequest retrieves current state of a room.
 * Topic: communication.room.get
 */
export interface GetRoomRequest {
  alkemio_room_id: AlkemioRoomID;
}
/**
 * GetRoomResponse returns room details with members and messages.
 */
export interface GetRoomResponse {
  BaseResponse: BaseResponse;
  alkemio_room_id: AlkemioRoomID;
  display_name: string;
  member_actor_ids: AlkemioActorID[];
  messages: MessageDto[];
}
/**
 * UpdateRoomRequest updates room metadata.
 * Topic: communication.room.update
 */
export interface UpdateRoomRequest {
  alkemio_room_id: AlkemioRoomID;
  name?: string;
  topic?: string;
  is_public?: boolean;
  avatar_url?: string;
  join_rule?: JoinRule;
}
/**
 * UpdateRoomResponse confirms the update.
 */
export interface UpdateRoomResponse {
  BaseResponse: BaseResponse;
}
/**
 * DeleteRoomRequest archives or deletes a room.
 * Topic: communication.room.delete
 */
export interface DeleteRoomRequest {
  alkemio_room_id: AlkemioRoomID;
  reason?: string;
}
/**
 * DeleteRoomResponse confirms deletion.
 */
export interface DeleteRoomResponse {
  BaseResponse: BaseResponse;
}
/**
 * ListRoomsRequest retrieves all rooms (admin operation).
 * Topic: communication.room.list
 */
export interface ListRoomsRequest {
  cursor?: string;
}
/**
 * ListRoomsResponse returns paginated room list.
 */
export interface ListRoomsResponse {
  BaseResponse: BaseResponse;
  alkemio_room_ids: AlkemioRoomID[];
  next_cursor?: string;
}

//////////
// source: space.go

/**
 * SpaceChildDto represents a child room or subspace within a space.
 */
export interface SpaceChildDto {
  /**
   * ChildID is the AlkemioRoomID of a child room or AlkemioContextID of a subspace.
   */
  child_id: string;
  is_space: boolean;
  order?: string;
  suggested?: boolean;
}
/**
 * CreateSpaceRequest creates a new Matrix Space for an Alkemio context.
 * Topic: communication.space.create
 */
export interface CreateSpaceRequest {
  alkemio_context_id: AlkemioContextID;
  name: string;
  topic?: string;
  avatar_url?: string;
  parent_context_id?: AlkemioContextID;
  join_rule?: JoinRule;
  initial_members?: AlkemioActorID[];
}
/**
 * CreateSpaceResponse confirms space creation.
 */
export interface CreateSpaceResponse {
  BaseResponse: BaseResponse;
}
/**
 * GetSpaceRequest retrieves current state of a space.
 * Topic: communication.space.get
 */
export interface GetSpaceRequest {
  alkemio_context_id: AlkemioContextID;
}
/**
 * GetSpaceResponse returns space details.
 */
export interface GetSpaceResponse {
  BaseResponse: BaseResponse;
  alkemio_context_id: AlkemioContextID;
  display_name: string;
  topic?: string;
  avatar_url?: string;
  join_rule: JoinRule;
  member_actor_ids: AlkemioActorID[];
  children: SpaceChildDto[];
  parent_context_id?: AlkemioContextID;
}
/**
 * UpdateSpaceRequest updates space metadata.
 * Topic: communication.space.update
 */
export interface UpdateSpaceRequest {
  alkemio_context_id: AlkemioContextID;
  name?: string;
  topic?: string;
  avatar_url?: string;
  join_rule?: JoinRule;
}
/**
 * UpdateSpaceResponse confirms the update.
 */
export interface UpdateSpaceResponse {
  BaseResponse: BaseResponse;
}
/**
 * DeleteSpaceRequest archives/deletes a space.
 * Topic: communication.space.delete
 */
export interface DeleteSpaceRequest {
  alkemio_context_id: AlkemioContextID;
  reason?: string;
}
/**
 * DeleteSpaceResponse confirms deletion.
 */
export interface DeleteSpaceResponse {
  BaseResponse: BaseResponse;
}
/**
 * ListSpacesRequest retrieves all spaces (admin operation).
 * Topic: communication.space.list
 */
export interface ListSpacesRequest {
  cursor?: string;
}
/**
 * ListSpacesResponse returns paginated space list.
 */
export interface ListSpacesResponse {
  BaseResponse: BaseResponse;
  alkemio_context_ids: AlkemioContextID[];
  next_cursor?: string;
}
/**
 * BatchAddSpaceMemberRequest adds an actor to multiple spaces.
 * Topic: communication.space.member.batch.add
 */
export interface BatchAddSpaceMemberRequest {
  actor_id: AlkemioActorID;
  alkemio_context_ids: AlkemioContextID[];
}
/**
 * BatchAddSpaceMemberResponse returns per-space results.
 */
export interface BatchAddSpaceMemberResponse {
  BaseResponse: BaseResponse;
  /**
   * Results maps AlkemioContextID (string) to operation result.
   */
  results?: { [key: string]: BaseResponse};
}
/**
 * BatchRemoveSpaceMemberRequest removes an actor from multiple spaces.
 * Topic: communication.space.member.batch.remove
 */
export interface BatchRemoveSpaceMemberRequest {
  actor_id: AlkemioActorID;
  alkemio_context_ids: AlkemioContextID[];
  reason?: string;
}
/**
 * BatchRemoveSpaceMemberResponse returns per-space results.
 */
export interface BatchRemoveSpaceMemberResponse {
  BaseResponse: BaseResponse;
  results?: { [key: string]: BaseResponse};
}

//////////
// source: types.go
/*
Package dto defines public Data Transfer Objects for the RabbitMQ protocol.
*/

/**
 * AlkemioRoomID is a UUID v4 or v7 identifying a room in Alkemio.
 * The adapter maps this to a Matrix room ID via room alias.
 */
export type AlkemioRoomID = string;
/**
 * AlkemioActorID is a UUID v4 or v7 identifying an actor (user or bot) in Alkemio.
 * The adapter maps this to a Matrix user ID.
 */
export type AlkemioActorID = string;
/**
 * MessageID is an opaque string identifier for a message.
 * Internally maps to Matrix Event ID.
 */
export type MessageID = string;
/**
 * ReactionID is an opaque string identifier for a reaction.
 * Internally maps to Matrix Event ID.
 */
export type ReactionID = string;
/**
 * AlkemioContextID is a UUID v4 or v7 identifying a context (Space/Subspace) in Alkemio.
 * The adapter maps this to a Matrix Space room.
 */
export type AlkemioContextID = string;
/**
 * RoomType defines the type of room to create.
 */
export type RoomType = string;
/**
 * RoomTypeCommunity is a general community room.
 */
export const RoomTypeCommunity: RoomType = "community";
/**
 * RoomTypeDirect is a direct message room between exactly 2 actors.
 */
export const RoomTypeDirect: RoomType = "direct";
/**
 * JoinRule defines access control for rooms and spaces.
 */
export type JoinRule = string;
/**
 * JoinRulePublic allows anyone to join.
 */
export const JoinRulePublic: JoinRule = "public";
/**
 * JoinRuleInvite requires an invitation to join.
 */
export const JoinRuleInvite: JoinRule = "invite";
/**
 * JoinRuleRestricted allows members of parent space to join (MSC3083).
 */
export const JoinRuleRestricted: JoinRule = "restricted";
