// Code generated by tygo. DO NOT EDIT.

//////////
// source: actor.go

/**
 * ActorRegisterPayload represents the payload for registering an actor.
 */
export interface ActorRegisterPayload {
  BaseMatrixAdapterEventPayload: BaseMatrixAdapterEventPayload;
  actorId: string;
  displayName: string;
}
/**
 * ActorRegisterResponsePayload represents the response after registering an actor.
 */
export interface ActorRegisterResponsePayload {
  BaseResponse: BaseResponse;
  matrixId: string;
}

//////////
// source: actor_dm.go

/**
 * ActorStartDirectMessagingPayload represents the payload to start a DM.
 */
export interface ActorStartDirectMessagingPayload {
  BaseMatrixAdapterEventPayload: BaseMatrixAdapterEventPayload;
  receiverActorID: string;
  initiatingActorID: string;
}
/**
 * ActorStartDirectMessagingResponsePayload represents the response for starting a DM.
 */
export interface ActorStartDirectMessagingResponsePayload {
  BaseResponse: BaseResponse;
  /**
   * RoomID is the ID of the DM room.
   */
  roomID: string;
  /**
   * IsNew indicates if the room was just created or already existed.
   */
  isNew: boolean;
}
/**
 * ActorStopDirectMessagingPayload represents the payload to stop a DM (leave/forget).
 */
export interface ActorStopDirectMessagingPayload {
  BaseMatrixAdapterEventPayload: BaseMatrixAdapterEventPayload;
  receiverActorID: string;
  initiatingActorID: string;
}
/**
 * ActorStopDirectMessagingResponsePayload represents the response for stopping a DM.
 */
export interface ActorStopDirectMessagingResponsePayload {
  BaseResponse: BaseResponse;
}
/**
 * ActorRoomsDirectPayload represents the request to list DM rooms for an actor.
 */
export interface ActorRoomsDirectPayload {
  BaseMatrixAdapterEventPayload: BaseMatrixAdapterEventPayload;
  actorID: string;
}
/**
 * ActorRoomsDirectResponse represents the list of DM rooms.
 */
export interface ActorRoomsDirectResponse {
  BaseResponse: BaseResponse;
  /**
   * Map of OtherActorID -> RoomID
   */
  directRooms: { [key: string]: string};
}

//////////
// source: actor_rooms.go

/**
 * ActorAddToRoomsPayload represents the payload for adding an actor to multiple rooms.
 */
export interface ActorAddToRoomsPayload {
  BaseMatrixAdapterEventPayload: BaseMatrixAdapterEventPayload;
  roomIDs: string[];
  actorID: string;
}
/**
 * ActorAddToRoomsResponsePayload represents the response for adding an actor to rooms.
 */
export interface ActorAddToRoomsResponsePayload {
  BaseResponse: BaseResponse;
  failedRooms?: string[];
  createdRooms?: string[]; // If rooms were created on the fly? Unlikely, but keeping generic.
}
/**
 * ActorRemoveFromRoomsPayload represents the payload for removing an actor from multiple rooms.
 */
export interface ActorRemoveFromRoomsPayload {
  BaseMatrixAdapterEventPayload: BaseMatrixAdapterEventPayload;
  roomIDs: string[];
  actorID: string;
}
/**
 * ActorRemoveFromRoomsResponsePayload represents the response for removing an actor from rooms.
 */
export interface ActorRemoveFromRoomsResponsePayload {
  BaseResponse: BaseResponse;
  failedRooms?: string[];
}
/**
 * ActorRoomsPayload represents the request to list rooms for an actor.
 */
export interface ActorRoomsPayload {
  BaseMatrixAdapterEventPayload: BaseMatrixAdapterEventPayload;
  actorID: string;
}
/**
 * ActorRoomsResponsePayload represents the list of rooms an actor is in.
 */
export interface ActorRoomsResponsePayload {
  BaseResponse: BaseResponse;
  roomIDs: string[];
}

//////////
// source: admin.go

/**
 * AdminAllRoomsPayload represents the request to list all rooms (admin only).
 */
export interface AdminAllRoomsPayload {
  BaseMatrixAdapterEventPayload: BaseMatrixAdapterEventPayload;
}
/**
 * AdminAllRoomsResponse represents the list of all rooms.
 */
export interface AdminAllRoomsResponse {
  BaseResponse: BaseResponse;
  rooms: RoomDetailsResponse[];
}
/**
 * AdminReplicateRoomMembershipPayload represents the request to replicate membership from one room to another.
 */
export interface AdminReplicateRoomMembershipPayload {
  BaseMatrixAdapterEventPayload: BaseMatrixAdapterEventPayload;
  targetRoomID: string;
  sourceRoomID: string;
  actorToPrioritize: string;
}
/**
 * AdminReplicateRoomMembershipResponsePayload represents the response for replication.
 */
export interface AdminReplicateRoomMembershipResponsePayload {
  BaseResponse: BaseResponse;
  addedUsers: string[];
  failedUsers: string[];
}

//////////
// source: base.go

/**
 * BaseMatrixAdapterEventPayload represents the common fields for all Matrix adapter events.
 */
export interface BaseMatrixAdapterEventPayload {
  /**
   * The Actor ID (UUID) of the user who triggered the event.
   */
  triggeredBy: string;
}

//////////
// source: error.go

/**
 * ErrorCode represents categorized error types for programmatic handling.
 */
export type ErrorCode = string;
/**
 * ErrorCodeInvalidPayload indicates JSON parsing or schema validation failed.
 */
export const ErrorCodeInvalidPayload: ErrorCode = "INVALID_PAYLOAD";
/**
 * ErrorCodeValidationError indicates business validation failed (e.g., invalid UUID format).
 */
export const ErrorCodeValidationError: ErrorCode = "VALIDATION_ERROR";
/**
 * ErrorCodeNotFound indicates the referenced entity does not exist.
 */
export const ErrorCodeNotFound: ErrorCode = "NOT_FOUND";
/**
 * ErrorCodePermissionDenied indicates the operation is not permitted.
 */
export const ErrorCodePermissionDenied: ErrorCode = "PERMISSION_DENIED";
/**
 * ErrorCodeMatrixError indicates a Matrix SDK/homeserver error.
 */
export const ErrorCodeMatrixError: ErrorCode = "MATRIX_ERROR";
/**
 * ErrorCodeInternalError indicates an unexpected system error.
 */
export const ErrorCodeInternalError: ErrorCode = "INTERNAL_ERROR";
/**
 * ErrorResponse contains structured error information.
 */
export interface ErrorResponse {
  code: ErrorCode;
  message: string;
}
/**
 * BaseResponse is the standard response structure for all command responses.
 * Operations that return only status use this directly.
 * Operations with additional data embed this struct.
 */
export interface BaseResponse {
  success: boolean;
  error?: ErrorResponse;
}

//////////
// source: event.go

/**
 * MessageReceivedPayload represents the event when a message is received.
 */
export interface MessageReceivedPayload {
  roomId: string;
  roomName: string;
  message: Message;
  actorID: string; // The actor who received the message (the bot)
  communityId?: string;
}
/**
 * Message represents a Matrix message event.
 */
export interface Message {
  id: string;
  message: string;
  threadID?: string;
  sender: string;
  timestamp: number /* int64 */;
  reactions: Reaction[];
}
/**
 * Reaction represents a reaction to a message.
 */
export interface Reaction {
  id: string;
  emoji: string;
  sender: string;
  timestamp: number /* int64 */;
  messageId: string;
}

//////////
// source: room.go

/**
 * RoomCreatePayload represents the payload to create a room.
 */
export interface RoomCreatePayload {
  BaseMatrixAdapterEventPayload: BaseMatrixAdapterEventPayload;
  roomName: string;
  metadata?: { [key: string]: string};
}
/**
 * RoomCreateResponsePayload represents the response for room creation.
 */
export interface RoomCreateResponsePayload {
  BaseResponse: BaseResponse;
  roomId: string;
}
/**
 * RoomInvitePayload is deprecated in favor of ActorAddToRoomsPayload.
 * Keeping it for now if needed for internal logic, but should be phased out.
 */
export interface RoomInvitePayload {
  BaseMatrixAdapterEventPayload: BaseMatrixAdapterEventPayload;
  inviteeId: string;
  roomId: string;
}
/**
 * RoomInviteResponsePayload represents the response for room invitation.
 */
export interface RoomInviteResponsePayload {
  BaseResponse: BaseResponse;
}

//////////
// source: room_manage.go

/**
 * RoomDeletePayload represents the payload to delete (leave/forget) a room.
 */
export interface RoomDeletePayload {
  BaseMatrixAdapterEventPayload: BaseMatrixAdapterEventPayload;
  roomID: string;
}
/**
 * RoomDeleteResponsePayload represents the response for room deletion.
 */
export interface RoomDeleteResponsePayload {
  BaseResponse: BaseResponse;
}
/**
 * RoomDetailsPayload represents the payload to get room details.
 */
export interface RoomDetailsPayload {
  BaseMatrixAdapterEventPayload: BaseMatrixAdapterEventPayload;
  roomID: string;
  withState?: boolean;
}
/**
 * RoomDetailsResponse represents the room details.
 */
export interface RoomDetailsResponse {
  BaseResponse: BaseResponse;
  roomID: string;
  name: string;
  topic: string;
  alias?: string;
  isDirect: boolean;
  joinedCount: number /* int */;
  state?: { [key: string]: string}; // Key-Value pairs of state events if requested
}
/**
 * RoomMembersPayload represents the payload to get room members.
 */
export interface RoomMembersPayload {
  BaseMatrixAdapterEventPayload: BaseMatrixAdapterEventPayload;
  roomID: string;
}
/**
 * RoomMembersResponse represents the list of room members.
 */
export interface RoomMembersResponse {
  BaseResponse: BaseResponse;
  roomID: string;
  userIDs: string[]; // Matrix User IDs
}
/**
 * RoomUpdateStatePayload represents the payload to update room state (name, topic, etc).
 */
export interface RoomUpdateStatePayload {
  BaseMatrixAdapterEventPayload: BaseMatrixAdapterEventPayload;
  roomID: string;
  name?: string;
  topic?: string;
  alias?: string;
}
/**
 * RoomUpdateStateResponse represents the response for state update.
 */
export interface RoomUpdateStateResponse {
  BaseResponse: BaseResponse;
}

//////////
// source: room_message.go

/**
 * RoomMessageSendPayload represents the payload to send a message.
 */
export interface RoomMessageSendPayload {
  BaseMatrixAdapterEventPayload: BaseMatrixAdapterEventPayload;
  roomID: string;
  senderActorID: string;
  message: string;
}
/**
 * RoomMessageSendResponse represents the response for sending a message.
 */
export interface RoomMessageSendResponse {
  BaseResponse: BaseResponse;
  eventID: string;
}
/**
 * RoomMessageSendReplyPayload represents the payload to reply to a message/thread.
 */
export interface RoomMessageSendReplyPayload {
  BaseMatrixAdapterEventPayload: BaseMatrixAdapterEventPayload;
  roomID: string;
  senderActorID: string;
  threadID: string; // The Event ID of the parent message
  message: string;
}
/**
 * RoomMessageSendReplyResponse represents the response for sending a reply.
 */
export interface RoomMessageSendReplyResponse {
  BaseResponse: BaseResponse;
  eventID: string;
}
/**
 * RoomMessageDeletePayload represents the payload to redact/delete a message.
 */
export interface RoomMessageDeletePayload {
  BaseMatrixAdapterEventPayload: BaseMatrixAdapterEventPayload;
  roomID: string;
  senderActorID: string; // Who is deleting it (must be sender or admin)
  eventID: string;
  reason?: string;
}
/**
 * RoomMessageDeleteResponse represents the response for message deletion.
 */
export interface RoomMessageDeleteResponse {
  BaseResponse: BaseResponse;
}
/**
 * RoomMessageAddReactionPayload represents the payload to add a reaction.
 */
export interface RoomMessageAddReactionPayload {
  BaseMatrixAdapterEventPayload: BaseMatrixAdapterEventPayload;
  roomID: string;
  senderActorID: string;
  messageID: string; // Event ID to react to
  emoji: string;
}
/**
 * RoomMessageAddReactionResponse represents the response for adding a reaction.
 */
export interface RoomMessageAddReactionResponse {
  BaseResponse: BaseResponse;
  eventID: string;
}
/**
 * RoomMessageRemoveReactionPayload represents the payload to remove a reaction.
 */
export interface RoomMessageRemoveReactionPayload {
  BaseMatrixAdapterEventPayload: BaseMatrixAdapterEventPayload;
  roomID: string;
  senderActorID: string;
  messageID: string;
  emoji: string; // Needed to find the reaction event to redact
}
/**
 * RoomMessageRemoveReactionResponse represents the response for removing a reaction.
 */
export interface RoomMessageRemoveReactionResponse {
  BaseResponse: BaseResponse;
}
/**
 * RoomMessageDetailsPayload represents the payload to get message details.
 */
export interface RoomMessageDetailsPayload {
  BaseMatrixAdapterEventPayload: BaseMatrixAdapterEventPayload;
  roomID: string;
  eventID: string;
}
/**
 * RoomMessageDetailsResponse represents the message details.
 */
export interface RoomMessageDetailsResponse {
  BaseResponse: BaseResponse;
  Message: Message;
}
