export enum AlkemioErrorStatus {
  NOT_SUPPORTED = 'NOT_SUPPORTED',
  MATRIX_NOT_AVAILABLE = 'MATRIX_NOT_AVAILABLE',
  MATRIX_LOGIN_FAILED = 'MATRIX_LOGIN_FAILED',
  MATRIX_REGISTRATION_FAILED = 'MATRIX_REGISTRATION_FAILED',
  MATRIX_MEMBERSHIP_ERROR = 'MATRIX_MEMBERSHIP_ERROR',
  MATRIX_AGENT_POOL_ERROR = 'MATRIX_AGENT_POOL_ERROR',
  MATRIX_ENTITY_NOT_FOUND_ERROR = 'MATRIX_ENTITY_NOT_FOUND_ERROR',
  NOT_ENABLED = 'NOT_ENABLED',
  BOOTSTRAP_FAILED = 'BOOTSTRAP_FAILED',
}
